# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:GdzSm0s=,iv:jCsusoZ3UIdkCqJ0YFjJ5Do+KgT5u9TzJNVAHwXk9S0=,tag:kF3WWTvn6yTHWllq+hr6LA==,type:str]
    admin-password: ENC[AES256_GCM,data:oOowvRX9X8BAAp8N2629Nls=,iv:OFdAASRhou5pB5ZUWXl0ii9ENT++brwGWhngAiCwIQI=,tag:vCtwCXC7KfsABpya9Kfqdg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGtPWhYMEiYAtyH+1SMA3UmHIQ75Ps0Ip0EarCbvOBZq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9MOTd1dyAxTDI4
            RjVPc0FlczdtRDZ4Y3NndXNyRUxXZWtDVmcySC9FY2YrV3FLT2lNCko0bUhQbUpI
            M0xyMjFFaHRNc0cvZGZEcWxrVHFXYzZPVmNzK0E5RkNkdU0KLS0tIHB3VE5qQ1ow
            VGhFU3NyaWQ2dFY3OGNITnBHc2xFTWVTRmRkTk1YVGxQS1UKdLgt24g9QUisQknd
            qLCuu31FK6PgBYob847JDYYtPsu/q1uYUQIt4m84LTeFbJOpd3YNbuzmCQdNABdu
            jTXKWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kj3zgfq2wxds0qf30wv4qdcs0u4a8xtf92d9f28gl8kqha4mcgmqgd8e3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWF5UHI3MHZCbGVyT1ZN
            SGVEak1XbXRGc1lxNnZ0dW9kbVdkOUt2THdVCkthOUExeGlvVDcrMjlJUjFwaUNG
            UjFieGk1QUY0aTRLbFdCaEppaFllaE0KLS0tIHBNbGhWQlhScFdRRkVWWHp3NGx6
            eXVJaTRqbk5yUllKVEpNZ2kxMm8yREkKYWxP3kkSKuJi8mZZTNs5vk7gvsor8bJq
            wZ9Uw87KzAlCrJEawbxxQIFTX86m3HOqI1ky3VcB9bekvBLQubnjUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T20:29:46Z"
    mac: ENC[AES256_GCM,data:Z+EkFtDZkmLJmJXZcIYRt5BpnCAhyu5bpAB14E8AHgYA3Nj8UNXaXpW7XqY0CZNxqNxf4GhVbfGNdSNvYseVrWyAkgVz58McmchDTtYNvbKcnWdrToth4O8AvcB7XZVssEk/p9JfyndqCpGDvwKNdK0kL2HJok+wIbNpK3FwsE8=,iv:MfiAxNbLxMlLugVPYQaoVUfaeFDOBMIGJF5nCjEjfQk=,tag:0gCGW/rNtSJ9cMNRhL2kbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
