# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: pihole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:K21KQBYwdakD6eE45A==,iv:LZK47KZOw573mqIKWJJAOgo0dTBA3UU5c4GAWvzr+8I=,tag:8cbLnWNhpNWpPJqIGcbpZA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGtPWhYMEiYAtyH+1SMA3UmHIQ75Ps0Ip0EarCbvOBZq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9MOTd1dyBvNlZV
            cmo5NlExTy8zbi9ER01mNHFZOTYycXFpQll6RksySWZCSzk4WlNRCjJwR3ZOLzNC
            TGd6S1ZEQ0syNng0TG5RTmwxNm9RcC81bDJCOG9lRVVkaGsKLS0tIGN2R1c4WCto
            YWJOZHVpa1RXUHdJazFxa0JuMkMvVDZFS0dzNGR2WGlUSEEKqm8H2RryNdUpWea2
            EDWxopPKLisVDEj8FqwUJoIS+awGdfajutTOIDQXmV7EupF4GY3K3P9Bj58u+MA+
            2lm0Jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kj3zgfq2wxds0qf30wv4qdcs0u4a8xtf92d9f28gl8kqha4mcgmqgd8e3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQzZ5REo2ZnZGbUhCeHFn
            VTlnTFBqZm9mYWordmFuakVYZ3pzZTIxaHlZCjMwQVRJN09MVzFxTlpIU1d2dC9t
            TG5INzBUNGRsU0VhTEtqYWpEQlllbGMKLS0tIDFEMWJvVmEvME0xUG5TNmt5dnlz
            M0VCL2F3T0svK0wxSmVoMTVhalg3eWcK9LV2UvWVrcfzuh9tGLF4EEVBGfjsPlb0
            bVJWBQ6ff5qWS8nbEQQ+O8S7UK5Cx91oV3hVu8gnmKuC4Jd8YIYw9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T21:20:42Z"
    mac: ENC[AES256_GCM,data:tqoZsz6EDZoi+CzyxAHoM8DyQTGUEgds77i/U649gNL0BAAzB5+R5cfcqBqak6uI/nh8VwUgSOzc78+BFH+FCxheu9xCGBfT9ERj6fB+BtRU4IRgkAfSjLQceMBQvIBu8RGDSvjxN0bdRl/ZfDsgALoe6oXvSbCn7W+iJICJ09I=,iv:YYu6kngvhMnajrrje4eo6QFgBiu68hsfnzFl9vNcNJo=,tag:I89xW6xEDOWi19YhcrgRJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGtPWhYMEiYAtyH+1SMA3UmHIQ75Ps0Ip0EarCbvOBZq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9MOTd1dyBvNlZV
            cmo5NlExTy8zbi9ER01mNHFZOTYycXFpQll6RksySWZCSzk4WlNRCjJwR3ZOLzNC
            TGd6S1ZEQ0syNng0TG5RTmwxNm9RcC81bDJCOG9lRVVkaGsKLS0tIGN2R1c4WCto
            YWJOZHVpa1RXUHdJazFxa0JuMkMvVDZFS0dzNGR2WGlUSEEKqm8H2RryNdUpWea2
            EDWxopPKLisVDEj8FqwUJoIS+awGdfajutTOIDQXmV7EupF4GY3K3P9Bj58u+MA+
            2lm0Jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kj3zgfq2wxds0qf30wv4qdcs0u4a8xtf92d9f28gl8kqha4mcgmqgd8e3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQzZ5REo2ZnZGbUhCeHFn
            VTlnTFBqZm9mYWordmFuakVYZ3pzZTIxaHlZCjMwQVRJN09MVzFxTlpIU1d2dC9t
            TG5INzBUNGRsU0VhTEtqYWpEQlllbGMKLS0tIDFEMWJvVmEvME0xUG5TNmt5dnlz
            M0VCL2F3T0svK0wxSmVoMTVhalg3eWcK9LV2UvWVrcfzuh9tGLF4EEVBGfjsPlb0
            bVJWBQ6ff5qWS8nbEQQ+O8S7UK5Cx91oV3hVu8gnmKuC4Jd8YIYw9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T21:20:42Z"
    mac: ENC[AES256_GCM,data:tqoZsz6EDZoi+CzyxAHoM8DyQTGUEgds77i/U649gNL0BAAzB5+R5cfcqBqak6uI/nh8VwUgSOzc78+BFH+FCxheu9xCGBfT9ERj6fB+BtRU4IRgkAfSjLQceMBQvIBu8RGDSvjxN0bdRl/ZfDsgALoe6oXvSbCn7W+iJICJ09I=,iv:YYu6kngvhMnajrrje4eo6QFgBiu68hsfnzFl9vNcNJo=,tag:I89xW6xEDOWi19YhcrgRJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
