# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: pihole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Ga+tFL9fYH0HHX5U2g==,iv:vBjkPA5dQsUFrT+fCRzfOn8krg4HJAJSRp2qXDNw/sM=,tag:LfyztLb7A1digB30QTK5+w==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGtPWhYMEiYAtyH+1SMA3UmHIQ75Ps0Ip0EarCbvOBZq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9MOTd1dyBSbmF4
            bjJmdGZtWjRtc01XMUJHQWg4NE13WitEZC9OTzRaeCtScWJnSFc4CjNYQjdWRlZC
            STBXdVJXWnFmUFpCRmRPaE9vcWcweDM0NjhmY0IveHVXQjQKLS0tIHRvRnpuWVhY
            ckwxc1hsMEo1d016NE0rNk1xZXl1RzdSYzNBZXgyM3FwVGMK4FeI6Y104+YtWRm6
            nCKhntuAV+ZLGtDaQtvyZbCWJCfSLTfQqye5/ZHmzzsV4KEJOk0n5j8siVJHB+tt
            Xz//eQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kj3zgfq2wxds0qf30wv4qdcs0u4a8xtf92d9f28gl8kqha4mcgmqgd8e3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OHN5bzgyK2RhWGJuU0ZQ
            R0dZOWpBZXVZbUkycThVMitEZXBYa0tpTlZnCm1ldGxVc210aVNjNmxBZ1FxZE9H
            QVdzVTBuTUlnTFo3RzZ6d2ZUcUxTaFkKLS0tIGVVeWlMQWphSWxhSFpNc2JQQTJD
            T0RSbG81OU5zMS9kdHpMYUluUm92dVEKZjEcDF2s8Or47bqNipSgl37gDcs0jQjR
            C0DmocBJr1uPgik33XqPk3Pbt0rF0HWT2XnjRljcXWeInXXGCMj0Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:58:33Z"
    mac: ENC[AES256_GCM,data:6tYFJy66C9orjQwg2RDbOdj70rfjVXJZBP263/nbZG7dYjJxmSahp8mgFlvCpBjl4yfddwwBnhVMKTo4ywGTtEhJrHg+quX4ZyDuGOIl9qtOF0iqkOcgwLxJPbG81BPTnncg86r354NZfNAKursoPTg5J/DTu4caVua4mnn4UeQ=,iv:fYoD3GSWwgJGg4zbonDjMHQN+EHUch2e8nfyqx+bLoQ=,tag:rfvTxMu8sLCyHC1NaRPReA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGtPWhYMEiYAtyH+1SMA3UmHIQ75Ps0Ip0EarCbvOBZq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9MOTd1dyBSbmF4
            bjJmdGZtWjRtc01XMUJHQWg4NE13WitEZC9OTzRaeCtScWJnSFc4CjNYQjdWRlZC
            STBXdVJXWnFmUFpCRmRPaE9vcWcweDM0NjhmY0IveHVXQjQKLS0tIHRvRnpuWVhY
            ckwxc1hsMEo1d016NE0rNk1xZXl1RzdSYzNBZXgyM3FwVGMK4FeI6Y104+YtWRm6
            nCKhntuAV+ZLGtDaQtvyZbCWJCfSLTfQqye5/ZHmzzsV4KEJOk0n5j8siVJHB+tt
            Xz//eQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kj3zgfq2wxds0qf30wv4qdcs0u4a8xtf92d9f28gl8kqha4mcgmqgd8e3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OHN5bzgyK2RhWGJuU0ZQ
            R0dZOWpBZXVZbUkycThVMitEZXBYa0tpTlZnCm1ldGxVc210aVNjNmxBZ1FxZE9H
            QVdzVTBuTUlnTFo3RzZ6d2ZUcUxTaFkKLS0tIGVVeWlMQWphSWxhSFpNc2JQQTJD
            T0RSbG81OU5zMS9kdHpMYUluUm92dVEKZjEcDF2s8Or47bqNipSgl37gDcs0jQjR
            C0DmocBJr1uPgik33XqPk3Pbt0rF0HWT2XnjRljcXWeInXXGCMj0Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:58:33Z"
    mac: ENC[AES256_GCM,data:6tYFJy66C9orjQwg2RDbOdj70rfjVXJZBP263/nbZG7dYjJxmSahp8mgFlvCpBjl4yfddwwBnhVMKTo4ywGTtEhJrHg+quX4ZyDuGOIl9qtOF0iqkOcgwLxJPbG81BPTnncg86r354NZfNAKursoPTg5J/DTu4caVua4mnn4UeQ=,iv:fYoD3GSWwgJGg4zbonDjMHQN+EHUch2e8nfyqx+bLoQ=,tag:rfvTxMu8sLCyHC1NaRPReA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
